[tool.poetry]
authors = ["wr1 <8971152+wr1@users.noreply.github.com>"]
description = "A command line tool to fold and unfold Python projects for LLM interaction"
license = "MIT"
name = "cfold"
packages = [{include = "cfold", from = "."}]
readme = "README.md"
version = "0.1.3"

[tool.poetry.dependencies]
pytest-cov = ">5.0.0"
python = "^3.10"
pyyaml = "^6.0.2"
click = "^8.1.7"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
pytest = "^7.1.3"

[tool.poetry.scripts]
cfold = "cfold.cfold:cli"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
