[tool.poetry]
authors = ["Your Name <your.email@example.com>"]
description = "A command line tool"
license = "MIT"
name = "cfold"
packages = [{include = "cfold"}]
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.11"
# Add any other dependencies here, e.g.,
# requests = "^2.28.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"

[tool.poetry.scripts]
cfold = "cfold.cfold:main"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]