"""Handle sum command for cfold."""

from pathlib import Path
from typing import List

import pyperclip
from rich.console import Console
from rich.tree import Tree

from ..summarization.sum_codebases import sum_codebases


def sum(
    codebases: List[str],
    output: str = "summary.txt",
    include_tests: bool = False,
    clip: bool = False,
):
    """Summarize codebases using AST."""
    console = Console()
    if not codebases:
        codebases = ["."]
    paths = [Path(cb) for cb in codebases]
    summary, processed_files = sum_codebases(paths, include_tests)
    if processed_files:
        tree = Tree(f"Summarized [cyan]{len(processed_files)}[/cyan] files", guide_style="dim")
        for cb_path in paths:
            branch = tree.add(f"[yellow]{cb_path}[/yellow]")
            for f in sorted(processed_files):
                try:
                    branch.add(f"[green]{f.relative_to(cb_path)}[/green]")
                except ValueError:
                    branch.add(f"[green]{f}[/green]")
        console.print(tree)
    summary_with_header = (
        "# This is an LLM input file generated by cfold sum. Do not modify or update this file.\n\n"
        + summary
    )
    Path(output).write_text(summary_with_header, encoding="utf-8")
    if clip:
        pyperclip.copy(summary_with_header)
    console.print(
        f"Summary written to [cyan]{output}[/cyan]" + (" and copied to clipboard." if clip else ".")
    )
