"""Handle sum command for cfold."""

from pathlib import Path
from typing import List
from rich.console import Console
import pyperclip
from ..summarization.sum_codebases import sum_codebases


def sum(
    codebases: List[str],
    output: str = "summary.txt",
    include_tests: bool = False,
    clip: bool = False,
):
    """Summarize codebases using AST."""
    console = Console()
    if not codebases:
        codebases = ["."]
    paths = [Path(cb) for cb in codebases]
    summary = sum_codebases(paths, include_tests)
    summary_with_header = (
        "# This is an LLM input file generated by cfold sum. Do not modify or update this file.\n\n"
        + summary
    )
    Path(output).write_text(summary_with_header, encoding="utf-8")
    if clip:
        pyperclip.copy(summary_with_header)
    console.print(
        f"Summary written to [cyan]{output}[/cyan]"
        + (" and copied to clipboard." if clip else ".")
    )
